/**
 * 100 quirky, unique words that appear while waiting for AI response
 * Words are displayed randomly next to the loading cube
 */
export const loadingWords = [
  "Loading",
  "Analyzing",
  "Discombobulating",
  "Disseminating",
  "Contemplating",
  "Cogitating",
  "Ruminating",
  "Percolating",
  "Synthesizing",
  "Calibrating",
  "Triangulating",
  "Extrapolating",
  "Deciphering",
  "Pontificating",
  "Prognosticating",
  "Fabricating",
  "Orchestrating",
  "Formulating",
  "Calculating",
  "Deliberating",
  "Scrutinizing",
  "Investigating",
  "Interrogating",
  "Evaluating",
  "Aggregating",
  "Correlating",
  "Concatenating",
  "Amalgamating",
  "Articulating",
  "Brainstorming",
  "Channeling",
  "Choreographing",
  "Compiling",
  "Composing",
  "Configuring",
  "Conjuring",
  "Consulting",
  "Contextualizing",
  "Concocting",
  "Crystallizing",
  "Curating",
  "Debugging",
  "Decoding",
  "Deconstructing",
  "Deducing",
  "Delineating",
  "Demystifying",
  "Detecting",
  "Diagnosing",
  "Digitizing",
  "Distilling",
  "Divining",
  "Elaborating",
  "Elucidating",
  "Envisioning",
  "Excavating",
  "Executing",
  "Expanding",
  "Expediting",
  "Experimenting",
  "Exploring",
  "Fathoming",
  "Finalizing",
  "Fine-tuning",
  "Forecasting",
  "Generalizing",
  "Generating",
  "Harmonizing",
  "Hypothesizing",
  "Ideating",
  "Illuminating",
  "Imagining",
  "Indexing",
  "Inferring",
  "Initializing",
  "Innovating",
  "Inspecting",
  "Integrating",
  "Interpreting",
  "Iterating",
  "Manifesting",
  "Mapping",
  "Materializing",
  "Meditating",
  "Modulating",
  "Negotiating",
  "Optimizing",
  "Organizing",
  "Parsing",
  "Piecing together",
  "Pioneering",
  "Postulating",
  "Predicting",
  "Preparing",
  "Processing",
  "Quantifying",
  "Rationalizing",
  "Reasoning",
  "Recalibrating",
  "Recontextualizing",
  "Refactoring",
  "Rendering",
  "Resolving",
  "Retrieving",
  "Simulating",
  "Strategizing",
  "Streamlining",
  "Structuring",
  "Summarizing",
  "Theorizing",
  "Translating",
  "Unraveling",
  "Validating",
  "Visualizing",
];

/**
 * Get a random loading word
 */
export function getRandomLoadingWord(): string {
  return loadingWords[Math.floor(Math.random() * loadingWords.length)];
}

/**
 * Get a random word different from the current one
 */
export function getNextLoadingWord(currentWord: string): string {
  let nextWord = getRandomLoadingWord();
  // Ensure we don't get the same word twice in a row
  while (nextWord === currentWord && loadingWords.length > 1) {
    nextWord = getRandomLoadingWord();
  }
  return nextWord;
}
