"use node";

import { v } from "convex/values";
import { action } from "./_generated/server";
import { api } from "./_generated/api";

export const generateTitle = action({
  args: {
    conversationId: v.id("conversations"),
  },
  handler: async (ctx, args): Promise<string | null> => {
    // Get first few messages
    const messages = await ctx.runQuery(api.messages.getAll, {
      conversationId: args.conversationId,
    });

    // Need at least 2 messages to generate a title
    if (messages.length < 2) {
      return null;
    }

    // Take first 4 messages
    const firstMessages = messages.slice(0, 4);

    // Format for title generation
    const conversationText = firstMessages
      .map((msg) => `${msg.role}: ${msg.content}`)
      .join("\n");

    const titlePrompt = `Generate a brief, concise title (3-6 words) for this conversation. Only return the title, nothing else.

Conversation:
${conversationText}

Title:`;

    try {
      console.log("Starting title generation...");
      console.log("API Key present:", !!process.env.OPENROUTER_API_KEY);

      // Call OpenRouter API
      const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
          "HTTP-Referer": process.env.NEXT_PUBLIC_CONVEX_URL || "http://localhost:3000",
          "X-Title": "Feir Chat App",
        },
        body: JSON.stringify({
          model: "z-ai/glm-4-32b", // Use GLM-4-32B for title generation
          messages: [
            {
              role: "user",
              content: titlePrompt,
            },
          ],
          max_tokens: 15,
          temperature: 0.7,
        }),
      });

      console.log("Response status:", response.status);

      if (!response.ok) {
        const errorText = await response.text();
        console.error("OpenRouter API error:", errorText);
        return null;
      }

      const data = await response.json();
      console.log("OpenRouter response:", JSON.stringify(data, null, 2));

      // For reasoning models, the actual response is in reasoning field
      // For regular models, it's in content field
      const message = data.choices[0]?.message;
      console.log("Message object:", message);

      let title = message?.reasoning?.trim() || message?.content?.trim();

      console.log("Extracted title:", title);

      if (title) {
        // Remove quotes if present
        const cleanTitle = title.replace(/^["']|["']$/g, "");

        // Update conversation title with auto-generated flag
        await ctx.runMutation(api.conversations.updateTitle, {
          conversationId: args.conversationId,
          title: cleanTitle,
          isAutoGenerated: true,
        });

        console.log("Title updated successfully:", cleanTitle);
        return cleanTitle;
      }

      console.log("No title extracted from response");
      return null;
    } catch (error) {
      console.error("Title generation failed:", error);
      return null;
    }
  },
});
