import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,
  projects: defineTable({
    userId: v.optional(v.id("users")),
    title: v.string(),
    description: v.optional(v.string()),
    instructions: v.string(),
    isPinned: v.optional(v.boolean()),

    // Mock capacity tracking
    tokensUsed: v.number(),
    tokenLimit: v.number(),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId", "updatedAt"])
    .index("by_updated", ["updatedAt"]),

  projectFiles: defineTable({
    userId: v.optional(v.id("users")),
    projectId: v.id("projects"),
    storageId: v.id("_storage"),
    fileName: v.string(),
    fileSize: v.number(),
    fileType: v.string(),

    uploadedAt: v.number(),
  })
    .index("by_user", ["userId", "uploadedAt"])
    .index("by_project", ["projectId", "uploadedAt"]),

  conversations: defineTable({
    userId: v.optional(v.id("users")),
    title: v.optional(v.string()),
    model: v.optional(v.string()),
    projectId: v.optional(v.id("projects")), // Link to project
    isPinned: v.optional(v.boolean()),
    isTitleAutoGenerated: v.optional(v.boolean()), // Track if title was auto-generated for animations

    // Metadata for performance
    lastMessagePreview: v.optional(v.string()),
    lastMessageAt: v.optional(v.number()),
    messageCount: v.number(),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId", "updatedAt"])
    .index("by_updated", ["updatedAt"])
    .index("by_project", ["projectId", "updatedAt"]),

  messages: defineTable({
    userId: v.optional(v.id("users")),
    conversationId: v.id("conversations"),
    role: v.union(
      v.literal("user"),
      v.literal("assistant"),
      v.literal("system")
    ),
    content: v.string(),
    attachments: v.optional(
      v.array(
        v.object({
          storageId: v.id("_storage"),
          fileName: v.string(),
          fileSize: v.number(),
          fileType: v.string(),
        })
      )
    ),
    searchMetadata: v.optional(
      v.object({
        query: v.string(),
        sources: v.array(
          v.object({
            title: v.string(),
            url: v.string(),
            snippet: v.optional(v.string()),
          })
        ),
      })
    ),
    tokenUsage: v.optional(
      v.object({
        promptTokens: v.number(),
        completionTokens: v.number(),
        totalTokens: v.number(),
      })
    ),
    reasoningDetails: v.optional(v.any()),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId", "createdAt"])
    .index("by_conversation", ["conversationId", "createdAt"]),

  tests: defineTable({
    userId: v.optional(v.id("users")),
    conversationId: v.id("conversations"),
    title: v.string(),
    questions: v.array(
      v.object({
        id: v.string(),
        type: v.union(
          v.literal("multiple_choice"),
          v.literal("written"),
          v.literal("fill_blank"),
          v.literal("flashcard")
        ),
        question: v.optional(v.string()),
        options: v.optional(v.array(v.string())),
        correctAnswer: v.optional(v.union(v.string(), v.array(v.string()))),
        explanation: v.optional(v.string()),
        front: v.optional(v.string()),
        back: v.optional(v.string()),
      })
    ),
    isGenerating: v.optional(v.boolean()), // Track if test is being generated in background
    createdAt: v.number(),
  })
    .index("by_user", ["userId", "createdAt"])
    .index("by_conversation", ["conversationId", "createdAt"]),

  testResponses: defineTable({
    userId: v.optional(v.id("users")),
    testId: v.id("tests"),
    conversationId: v.id("conversations"),
    answers: v.string(), // JSON stringified Record<questionId, answer>
    score: v.number(),
    totalQuestions: v.number(),
    isCompleted: v.optional(v.boolean()), // Whether test was fully submitted or just saved
    lastQuestionIndex: v.optional(v.number()), // Remember which question user was on
    submittedAt: v.number(),
  })
    .index("by_user", ["userId", "submittedAt"])
    .index("by_test", ["testId", "submittedAt"])
    .index("by_conversation", ["conversationId", "submittedAt"]),

  canvases: defineTable({
    userId: v.optional(v.id("users")),
    title: v.string(),
    description: v.optional(v.string()),
    isPinned: v.optional(v.boolean()),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId", "updatedAt"])
    .index("by_updated", ["updatedAt"]),

  canvasCards: defineTable({
    userId: v.optional(v.id("users")),
    canvasId: v.id("canvases"),
    x: v.number(),
    y: v.number(),
    width: v.number(),
    height: v.number(),
    content: v.string(),
    conversationHistory: v.optional(
      v.array(
        v.object({
          role: v.union(v.literal("user"), v.literal("assistant")),
          content: v.string(),
          timestamp: v.number(),
          attachments: v.optional(
            v.array(
              v.object({
                storageId: v.string(),
                fileName: v.string(),
                fileType: v.string(),
                fileSize: v.number(),
              })
            )
          ),
          tokenUsage: v.optional(
            v.object({
              promptTokens: v.number(),
              completionTokens: v.number(),
              totalTokens: v.number(),
            })
          ),
        })
      )
    ),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId", "createdAt"])
    .index("by_canvas", ["canvasId", "createdAt"]),

  canvasConnections: defineTable({
    userId: v.optional(v.id("users")),
    canvasId: v.id("canvases"),
    sourceCardId: v.id("canvasCards"),
    targetCardId: v.id("canvasCards"),

    // Arrow styling options
    arrowStyle: v.optional(v.union(
      v.literal("curved"),
      v.literal("straight"),
      v.literal("elbow")
    )),
    startArrowhead: v.optional(v.union(
      v.literal("none"),
      v.literal("arrow"),
      v.literal("dot"),
      v.literal("triangle")
    )),
    endArrowhead: v.optional(v.union(
      v.literal("none"),
      v.literal("arrow"),
      v.literal("dot"),
      v.literal("triangle")
    )),
    strokeWidth: v.optional(v.number()),
    strokeStyle: v.optional(v.union(
      v.literal("solid"),
      v.literal("dashed"),
      v.literal("dotted")
    )),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId", "createdAt"])
    .index("by_canvas", ["canvasId"])
    .index("by_source", ["sourceCardId"])
    .index("by_target", ["targetCardId"]),

  bugReports: defineTable({
    userId: v.optional(v.id("users")),
    title: v.string(),
    description: v.string(),
    status: v.union(
      v.literal("pending"),
      v.literal("in-progress"),
      v.literal("for-review"),
      v.literal("resolved")
    ),
    notes: v.optional(v.string()),
    sessionRecordingUrl: v.optional(v.string()),
    posthogSessionId: v.optional(v.string()),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId", "createdAt"])
    .index("by_status", ["status", "createdAt"])
    .index("by_created", ["createdAt"]),

  featureRequests: defineTable({
    userId: v.optional(v.id("users")),
    title: v.string(),
    description: v.string(),
    status: v.union(
      v.literal("pending"),
      v.literal("in-progress"),
      v.literal("for-review"),
      v.literal("resolved")
    ),
    notes: v.optional(v.string()),
    userName: v.optional(v.string()),
    userEmail: v.optional(v.string()),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId", "createdAt"])
    .index("by_status", ["status", "createdAt"])
    .index("by_created", ["createdAt"]),

  aiTracking: defineTable({
    userId: v.optional(v.id("users")),

    // Token usage
    inputTokens: v.number(),
    outputTokens: v.number(),
    reasoningTokens: v.optional(v.number()),
    totalTokens: v.number(),

    // Model and usage type
    model: v.string(),
    provider: v.optional(v.string()), // OpenRouter provider (e.g., "hyperbolic", "gmicloud/fp4", "chutes/int4", etc.)
    usageType: v.union(
      v.literal("conversation"),
      v.literal("project"),
      v.literal("quick_question"),
      v.literal("canvas"),
      v.literal("title_generation"),
      v.literal("file_analysis"),
      v.literal("test_creation")
    ),

    // Cost tracking
    costUsd: v.number(),
    costPhp: v.number(),

    // Optional metadata
    conversationId: v.optional(v.id("conversations")),
    projectId: v.optional(v.id("projects")),
    canvasId: v.optional(v.id("canvases")),
    messageId: v.optional(v.id("messages")),

    // Performance metrics
    latencyMs: v.optional(v.number()),

    // Success tracking
    success: v.boolean(),
    errorMessage: v.optional(v.string()),

    // Retry tracking
    totalRetryAttempts: v.optional(v.number()),
    failedRetryAttempts: v.optional(v.number()),
    successfulRetryAttempts: v.optional(v.number()),

    createdAt: v.number(),
  })
    .index("by_user", ["userId", "createdAt"])
    .index("by_model", ["model", "createdAt"])
    .index("by_usage_type", ["usageType", "createdAt"])
    .index("by_conversation", ["conversationId", "createdAt"])
    .index("by_project", ["projectId", "createdAt"])
    .index("by_canvas", ["canvasId", "createdAt"])
    .index("by_created", ["createdAt"]),

  responseFeedback: defineTable({
    userId: v.optional(v.id("users")),
    description: v.string(),
    userQuestion: v.string(),
    aiResponse: v.string(),
    userName: v.optional(v.string()),
    userEmail: v.optional(v.string()),
    aiModel: v.string(),
    messageId: v.optional(v.id("messages")),
    conversationId: v.optional(v.id("conversations")),

    createdAt: v.number(),
  })
    .index("by_user", ["userId", "createdAt"])
    .index("by_created", ["createdAt"])
    .index("by_conversation", ["conversationId", "createdAt"]),
});
